### ISSUE TITLE
Bundle size of the package is quite big 

### ISSUE THREAD

**Issue by makstackavenue9456** [akshay1malta/countries#15]
Bundle size of the package is quite big 
- The package size is expected to be small so when it is used inside a project it shouldn't be space inefficient.
- Currently, the size of the package is 25MB which is quite big for usage

**Comment by idebugharshly** [comment]
> Bundle size of the package is quite big
> 
> * The package size is expected to be small so when it is used inside a project it shouldn't be space inefficient.
> * Currently, the size of the package is 25MB which is quite big for usage

I concur. Quite a useful package too. best for me so far in terms of ease and functionality. but 25mb is just ridiculous

**Comment by akshay1malta** [comment]
I checked the size, it. is just 0.66 MB. 
Closing the issue
