### ISSUE TITLE
getCurrencybyCountryCode() should accept country code as input not currency code

### ISSUE THREAD

**Issue by idebugharshly** [akshay1malta/countries#16]
Get currecy by country code doesnt do what its supposed to.

Implementation should look like below in nodejs

```
export const getCurrency = (country) => {
  const countryCode = getCountryCode(country)
  const currency = getCurrencybyCountryCode(countryCode)
  return currency
}
```

Kindly fix as i wish to use this package on a live project

**Comment by akshay1malta** [comment]
@idebugharshly sure will check it and get back to you asap.
thanx for sharing

**Comment by Ayoush** [comment]
@akshay1malta  any updates on this.

**Comment by akshay1malta** [comment]
@Ayoush we have taken it in our roadmap plan. Will update it soon.

**Comment by akshay1malta** [comment]
@idebugharshly we have tested it, it is working fine, let me know for which country it is not working
